server:
  port: 3344

spring:
  application:
    name: microservice-springcloud-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/tsubasatei/microservice-springcloud-config.git # github上面的git仓库名字