server:
  port: 9527

spring:
  application:
    name: microservice-springcloud-zuul-gateway

eureka:
  client: # 客户端注册进 eureka 服务列表内
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: gateway-9527
    prefer-ip-address: true # 访问路径可以显示IP地址

info:
  app.name: xt-microservice-springcloud
  company.name: www.xt.com
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}


zuul:
  routes:
    mydept.serviceId: microservice-springcloud-dept
    mydept.path: /mydept/**
#  ignored-services: microservice-springcloud-dept
  ignored-services: "*"
  prefix: /xt
